In [1]:

# DAY1 : Data Loading & First Look
# GOAL : Understand the shape and structure of our dataset
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/student_lifestyle.csv")

In [3]:
df.head()

,student_id,age,gender,year_of_study,field_of_study,stress_level,anxiety_score,sleep_hours,sleep_quality,mood_rating,...,screen_time_before_sleep,daily_social_media_hours,platform_usage,physical_activity,social_interaction_level,study_hours_per_day,class_attendance_pct,exam_score,GPA,academic_performance
0,1,22,Male,1,Arts,6,5,5.0,2.0,5.0,...,0.5,4.4,TikTok,6.0,5.1,NaN,69.7,59.1,1.90,51.0
1,2,21,Male,1,Engineering,5,5,5.9,3.0,6.0,...,1.0,2.1,Instagram,2.0,9.0,1.5,NaN,54.0,2.21,51.4
2,3,22,Female,1,Science,6,2,5.7,2.0,4.0,...,1.6,2.5,Both,3.9,6.7,NaN,73.0,64.7,2.33,58.1
3,4,24,Female,2,Computer Science,4,3,7.5,NaN,8.0,...,0.0,2.7,Both,6.5,7.5,1.8,81.0,70.6,2.78,71.9
4,5,21,Male,3,Science,6,4,6.3,2.0,5.0,...,NaN,3.4,Instagram,4.6,7.0,2.3,82.4,61.8,2.61,54.8

In [4]:
print("Dataset loaded successfully!")
print(f" rows: {df.shape[0]} ")
print(f"columns: {df.shape[1]}")

Dataset loaded successfully!
 rows: 1000
columns: 21

In [5]:
print("column info")
print(df.info())

column info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   student_id                1000 non-null   int64
 1   age                       1000 non-null   int64
 2   gender                    1000 non-null   object
 3   year_of_study             1000 non-null   int64
 4   field_of_study            1000 non-null   object
 5   stress_level              1000 non-null   int64
 6   anxiety_score             1000 non-null   int64
 7   sleep_hours               960 non-null    float64
 8   sleep_quality             970 non-null    float64
 9   mood_rating               970 non-null    float64
 10  daily_screen_time_hrs     950 non-null    float64
 11  screen_time_before_sleep  950 non-null    float64
 12  daily_social_media_hours  950 non-null    float64
 13  platform_usage            967 non-null    object
 14  physical_activity         960 non-null    float64
 15  social_interaction_level  960 non-null    float64
 16  study_hours_per_day       950 non-null    float64
 17  class_attendance_pct      960 non-null    float64
 18  exam_score                950 non-null    float64
 19  GPA                       939 non-null    float64
 20  academic_performance      970 non-null    float64
dtypes: float64(13), int64(5), object(3)
memory usage: 164.2+ KB
None

In [6]:
print(" Missing Values:")
missing = df.isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else " No missing values found!")

 Missing Values:
sleep_hours                 40
sleep_quality               30
mood_rating                 30
daily_screen_time_hrs       50
screen_time_before_sleep    50
daily_social_media_hours    50
platform_usage              33
physical_activity           40
social_interaction_level    40
study_hours_per_day         50
class_attendance_pct        40
exam_score                  50
GPA                         61
academic_performance        30
dtype: int64

In [7]:
print("Basic Statistics:")
df.describe()

Basic Statistics:

,student_id,age,year_of_study,stress_level,anxiety_score,sleep_hours,sleep_quality,mood_rating,daily_screen_time_hrs,screen_time_before_sleep,daily_social_media_hours,physical_activity,social_interaction_level,study_hours_per_day,class_attendance_pct,exam_score,GPA,academic_performance
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,960.000000,970.000000,970.000000,950.000000,950.000000,950.000000,960.000000,960.000000,950.000000,960.000000,950.000000,939.000000,970.000000
mean,500.500000,21.045000,2.26900,5.733000,5.747000,6.310000,2.403093,5.289691,3.960105,1.433263,2.862105,3.394062,6.235208,2.779053,79.640833,63.646632,2.541597,63.456495
std,288.819436,1.644287,1.07694,1.691914,1.966942,1.195012,1.129120,1.615711,1.548866,0.868564,1.127656,1.406849,1.304772,1.239563,8.414941,12.995261,0.519448,12.639402
min,1.000000,18.000000,1.00000,1.000000,1.000000,3.000000,1.000000,1.000000,0.100000,0.000000,0.000000,0.000000,2.000000,-0.600000,52.900000,24.800000,0.770000,18.400000
25%,250.750000,20.000000,1.00000,5.000000,5.000000,5.500000,1.000000,4.000000,3.000000,0.800000,2.100000,2.400000,5.300000,2.000000,74.100000,54.825000,2.200000,54.850000
50%,500.500000,21.000000,2.00000,6.000000,6.000000,6.300000,2.000000,5.000000,3.900000,1.400000,2.900000,3.400000,6.300000,2.800000,79.500000,63.800000,2.540000,63.200000
75%,750.250000,22.000000,3.00000,7.000000,7.000000,7.100000,3.000000,6.000000,4.800000,2.000000,3.600000,4.300000,7.100000,3.600000,85.300000,72.375000,2.910000,71.900000
max,1000.000000,26.000000,4.00000,13.000000,10.000000,10.000000,5.000000,10.000000,16.600000,4.200000,6.500000,7.300000,9.900000,7.100000,100.000000,100.000000,4.000000,97.300000

In [8]:
# Missing Value Summary

print("MISSING VALUE REPORT")

missing = df.isnull().sum()
missing_prct = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_prct.round(2)
})

print(missing_report[missing_report['Missing Count'] > 0])
print("=" * 45)
print(f"Total missing cells: {df.isnull().sum().sum()}")

MISSING VALUE REPORT
                          Missing Count  Missing %
sleep_hours                          40        4.0
sleep_quality                        30        3.0
mood_rating                          30        3.0
daily_screen_time_hrs                50        5.0
screen_time_before_sleep             50        5.0
daily_social_media_hours             50        5.0
platform_usage                       33        3.3
physical_activity                    40        4.0
social_interaction_level             40        4.0
study_hours_per_day                  50        5.0
class_attendance_pct                 40        4.0
exam_score                           50        5.0
GPA                                  61        6.1
academic_performance                 30        3.0
=============================================
Total missing cells: 594

In [9]:
for col in df.columns:
    print(f"\n {col}")
    print("="*20)
    print(f" type : {df[col].dtype}")
    print(f" null values : {df[col].isnull().sum()}")
    print(f" sample : {df[col].dropna().unique()[:5]}")
    print(f" sample_max : {df[col].dropna().unique().max()}")
    print(f" sample_min : {df[col].dropna().unique().min()}")

 student_id
====================
 type : int64
 null values : 0
 sample : [1 2 3 4 5]
 sample_max : 1000
 sample_min : 1

 age
====================
 type : int64
 null values : 0
 sample : [22 21 24 20 18]
 sample_max : 26
 sample_min : 18

 gender
====================
 type : object
 null values : 0
 sample : ['Male' 'Female' 'Other']
 sample_max : Other
 sample_min : Female

 year_of_study
====================
 type : int64
 null values : 0
 sample : [1 2 3 4]
 sample_max : 4
 sample_min : 1

 field_of_study
====================
 type : object
 null values : 0
 sample : ['Arts' 'Engineering' 'Science' 'Computer Science' 'Other']
 sample_max : Science
 sample_min : Arts

 stress_level
====================
 type : int64
 null values : 0
 sample : [6 5 4 8 9]
 sample_max : 13
 sample_min : 1

 anxiety_score
====================
 type : int64
 null values : 0
 sample : [5 2 3 4 9]
 sample_max : 10
 sample_min : 1

 sleep_hours
====================
 type : float64
 null values : 40
 sample : [5.  5.9 5.7 7.5 6.3]
 sample_max : 10.0
 sample_min : 3.0

 sleep_quality
====================
 type : float64
 null values : 30
 sample : [2. 3. 1. 4. 5.]
 sample_max : 5.0
 sample_min : 1.0

 mood_rating
====================
 type : float64
 null values : 30
 sample : [5. 6. 4. 8. 3.]
 sample_max : 10.0
 sample_min : 1.0

 daily_screen_time_hrs
====================
 type : float64
 null values : 50
 sample : [2.6 2.4 3.5 1.6 5.6]
 sample_max : 16.6
 sample_min : 0.1

 screen_time_before_sleep
====================
 type : float64
 null values : 50
 sample : [0.5 1.  1.6 0.  1.2]
 sample_max : 4.2
 sample_min : 0.0

 daily_social_media_hours
====================
 type : float64
 null values : 50
 sample : [4.4 2.1 2.5 2.7 3.4]
 sample_max : 6.5
 sample_min : 0.0

 platform_usage
====================
 type : object
 null values : 33
 sample : ['TikTok' 'Instagram' 'Both']
 sample_max : TikTok
 sample_min : Both

 physical_activity
====================
 type : float64
 null values : 40
 sample : [6.  2.  3.9 6.5 4.6]
 sample_max : 7.3
 sample_min : 0.0

 social_interaction_level
====================
 type : float64
 null values : 40
 sample : [5.1 9.  6.7 7.5 7. ]
 sample_max : 9.9
 sample_min : 2.0

 study_hours_per_day
====================
 type : float64
 null values : 50
 sample : [1.5 1.8 2.3 2.8 4.1]
 sample_max : 7.1
 sample_min : -0.6

 class_attendance_pct
====================
 type : float64
 null values : 40
 sample : [69.7 73.  81.  82.4 79.3]
 sample_max : 100.0
 sample_min : 52.9

 exam_score
====================
 type : float64
 null values : 50
 sample : [59.1 54.  64.7 70.6 61.8]
 sample_max : 100.0
 sample_min : 24.8

 GPA
====================
 type : float64
 null values : 61
 sample : [1.9  2.21 2.33 2.78 2.61]
 sample_max : 4.0
 sample_min : 0.77

 academic_performance
====================
 type : float64
 null values : 30
 sample : [51.  51.4 58.1 71.9 54.8]
 sample_max : 97.3
 sample_min : 18.4